-- In-Class Exercises

/*
Build a list of the 25 employees that appear first alphabetically by the name
of their country, and then by their last name. Include the ID, and both names,
but rename the id field to be called EmployeeID.
*/


/*
How Many records are there in the set if all NULL values are excluded from the
total_worth and is_management fields?
*/


/*
Create a list of the 5 highest worth employees from Canada, from most to least.
*/


/*
How many countries are represented in the data? What is the ratio of the unique
number of last names to the unique number of countries? Name the output columns:
countries, last_names, and ratio.
*/


/*
How many employees are either from Kenya or have a total worth greater than 47
but less than 51?
*/


/*
Produce a list of employees by last name, id, and email address only; where
*/


-- BONUS -----------------------------------------------------------------------

/*
I would like to give a 10% worth raise plus an extra 5 on top to all Canadian
employees who either have a current worth less than 10, or are not management.
Please produce a list of all employees meeting that criteria with their id, their
name, their current worth, and their future worth once they get the raise.
*/


/*
If I gave a 12% raise, how many new management employees would be in the
above 50 category?
*/
