-- In-Class Exercises
-- Please use the "company_employees_plus.db" database to answer all questions.

/*
Which counry accounts for the highest percentage of the population of the continent
it sits on?
*/


/*
How many records on the employee table contain a country where we do not
have any information on the country_master table?
*/


/*
Produce a dataset of all employees located in Africa, grouped by the company they
work for. Include the company name, the number of employees, and the average
total_worth for those employees. Put them in descending order by the number of
employees. Include only companies with more than 1 employee in Africa.
*/


/*
Breakdown the number of people by gender who work for a company with more than
1 person in the set, and who's total_worth is more than 5% over the average of
all employees.
*/


/*
Produce a dataset of all employees who are management, female, and have a higher
than country average worth. Include in this dataset the id, name, and email address
of the employees, and sort the list in order by last name.
*/
